function Playerstats({game}) {

    return(
        <div className = "player-stats">
        <h1>Player Stats</h1>
        <table className = 'quarters'>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Team</th>
                    <th>POS</th>
                    <th>MIN</th>
                    <th>SEC</th>
                    <th>FG</th>
                    <th>FGA</th>
                    <th>FG%</th>
                    <th>EFG%</th>
                    <th>2P</th>
                    <th>2PA</th>
                    <th>2P%</th>
                    <th>3P</th>
                    <th>3PA</th>
                    <th>3P%</th>
                    <th>FT</th>
                    <th>FTA</th>
                    <th>FT%</th>
                    <th>OREB</th>
                    <th>DREB</th>
                    <th>REB</th>
                    <th>AST</th>
                    <th>STL</th>
                    <th>BLK</th>
                    <th>TO</th>
                    <th>PTS</th>
                </tr>
                {game.PlayerGames.map((player, idx) => (
                    <tr key= {idx}>
                        <td>
                            <strong>{player.Name}</strong>
                        </td>
                        <td>
                            {player.Team}
                        </td>
                        <td>
                            {player.Position}
                        </td>
                        <td>
                            {player.Minutes}
                        </td>
                        <td>
                            {player.Seconds}
                        </td>
                        <td>
                            {player.FieldGoalsMade}
                        </td>
                        <td>
                            {player.FieldGoalsAttempted}
                        </td>
                        <td>
                            {player.FieldGoalsPercentage}%
                        </td>
                        <td>
                            {player.EffectiveFieldGoalsPercentage}%
                        </td>
                        <td>
                            {player.TwoPointersMade}
                        </td>
                        <td>
                            {player.TwoPointersAttempted}
                        </td>
                        <td>
                            {player.TwoPointersPercentage}%
                        </td>
                        <td>
                            {player.ThreePointersMade}
                        </td>
                        <td>
                            {player.ThreePointersAttempted}
                        </td>
                        <td>
                            {player.ThreePointersPercentage}%
                        </td>
                        <td>
                            {player.FreeThrowsMade}
                        </td>
                        <td>
                            {player.FreeThrowsAttempted}
                        </td>
                        <td>
                            {player.FreeThrowsPercentage}
                        </td>
                        <td>
                            {player.OffensiveRebounds}
                        </td>
                        <td>
                            {player.DefensiveRebounds}
                        </td>
                        <td>
                            {player.Rebounds}
                        </td>
                        <td>
                            {player.Assists}
                        </td>
                        <td>
                            {player.Steals}
                        </td>
                        <td>
                            {player.BlockedShots}
                        </td>
                        <td>
                            {player.Turnovers}
                        </td>
                        <td>
                            {player.Points}
                        </td>
                    </tr>
                ))} 
           </thead>
        </table>

        </div> 
        )
    }


export default Playerstats